site:
  title: InvenHost Docs
  start_page: invenhost::start.adoc
  robots: allow 
  url: https://doc.invenhost.com
  keys: 
    umami: 84b86573-caa2-4afd-8bde-b27962a8a18f
urls:
  html_extension_style: indexify
content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
  - url: https://github.com/invenhost/inventree-federation.git
    branches: main, dev
    start_path: docs
  - url: https://github.com/matmair/inventree-approval.git
    branches: main, dev
    start_path: docs
  - url: https://github.com/invenhost/plugins.git
    branches: [main, dev, v*]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - '@antora/lunr-extension'
