= Project Docs
Matthias Mair <code@mjmair.com>;

InvenHost is a project by @matmair that aims to enhance and extend the functionality of core InvenTree to support commercial and enterprise use cases.

NOTE: This project is not affiliated with InvenTree.

## Current Focus

I am currently focused on getting 3 internal plugins cleaned up and released in the following order:

1. Approvals
2. Marketplaces
3. Suppliers

There are 20+ private plugins that could be released at some point but that will depend on interest, feedback form the community and available time.
Specific areas of interest to me are deeper file integrations and interoperability.

### Plugins

#### Approvals

Adds a general-purpose approval system to InvenTree. It allows users to request approval for certain actions, and for others to approve or reject those requests. It is designed to be flexible and extensible and can be used to implement a wide range of approval workflows.

The current testing and development focus is on the ability to request approval for orders (especially purchase orders), the plugin by default blocks unapproved POs from being placed.

xref:plugins.adoc#inventree_approval[Read More], https://github.com/invenhost/plugins/issues/1[EPIC here]


#### Marketplaces

TIP: Slated for Q2 2024
https://github.com/invenhost/plugins/issues/2[EPIC here]


#### Suppliers

TIP: Slated for Q2 2024
EPIC is currently being formulated

#### Manufacturing Machines

TIP: Closed Beta active, Slated for Q4 2024
Integrations for the manufacturing floor, starting with PnP machines that speak camX or MQTT.


### Infrastructure

For successful operations of (a) plugin repository a few pieces are needed:

- Central documentation site (this 😅)
- Private PyPi index
- Licensing service for index access
- Telemetry service
- Management plugin for handling updates, telemetry, feedback and licensing
- CI templates / possibly infrastructure
- (?) Feedback mechanism / hub
- (?) Payments --> Stripe
- (?) IaC for the whole infrastructure
- (?) SecOps setup

There is a lot to prototype, develop and field-test. If this project comes to working conclusions, upstreaming is not out of the question.

[NOTE]
====
The InvenTree project is receiving generous credits by DigitalOcean via their open-source program so those could be used in the long term.

InvenHost is a separate org and running on my (matmair) personal accounts/credits.
====

## Licensing

Some of the plugins (and possibly services) will be closed source, some open.

The plan for each individual product will be outlined at the latest in the product docs as part of v1 releases. Please take that into consideration when taking part in alpha/beta programs.

## Bigger picture

InvenTree would not be viable as a sand-alone commercial product right now. Luckily it does not have to as the passionate members of the core team and community maintain it as part of their jobs or leisure time. That will not be sustainable in the long run, especially with the growing complexity of the project.

An ethical way to get that funding for individual developers would be paid plugins / subscriptions for private plugin repos.

The plan here is to test different models and the needed infrastructure in a low risk environment. I do not need this to succeed, I do not think it will in any reasonable time as I am not dependent on it in any way. Not losing money would be nice in the next 2-3 year.
